name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.4.0'
          cache: 'npm'
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/mmi22h03/public_html/portfolio-v2
            
            # Récupérer les dernières modifications
            git pull origin main
            
            # Installation et build
            npm ci
            npm run build
            
            # Arrêter l'ancienne application
            pm2 delete portfolio-v2 || true
            
            # Démarrer correctement avec PM2
            pm2 start .output/server/index.mjs --name "portfolio-v2"
            pm2 save
            
            # Permissions et redémarrage Apache
            sudo chown -R mmi22h03:www-data /home/mmi22h03/public_html/portfolio-v2/.output
            sudo chmod -R 775 /home/mmi22h03/public_html/portfolio-v2/.output
            sudo systemctl restart apache2
